### ISSUE TITLE
Return first argument invisibly for side effect functions

### ISSUE THREAD

**Issue by nanxstats** [Merck/metalite#114]
See <https://style.tidyverse.org/functions.html?q=invisible#return> for the rationale.

In particular, `print.meta_adam()`.

Probably in the next release.

**Comment by fb-elong** [comment]
Could you show me the line of code? I did not see `return()` function in `print.meta_adam()`

**Comment by nanxstats** [comment]
@fb-elong Perhaps the the link I pasted was not accurately anchored because it's the latter half of the section, but here is the the exact quote:

> If your function is called primarily for its side-effects (like printing, plotting, or saving to disk), it should return the first argument invisibly. This makes it possible to use the function as part of a pipe. print methods should usually do this, like this example from [httr](http://httr.r-lib.org/):

```r
print.url <- function(x, ...) {
  [cat](https://rdrr.io/r/base/cat.html)("Url: ", build_url(x), "\n", sep = "")
  [invisible](https://rdrr.io/r/base/invisible.html)(x)
}
```

**Comment by elong0527** [comment]
Got it. Would you want to create a PR?
