### ISSUE TITLE
Update default_parameter_ae.R due to inconsistency

### ISSUE THREAD

**Issue by wangben718** [Merck/metalite#136]
Need to update label of parameter in https://github.com/Merck/metalite/blob/08d52cdbe1b8a7893761ca8cfc97ad1a85504ab9/data-raw/default_parameter_ae.R#L41. Also check other parameters.

**Comment by nanxstats** [comment]
Is this issue fixed by https://github.com/Merck/metalite/pull/137 or do we still need follow up fixes?

**Comment by wangben718** [comment]
Related to #137
