### ISSUE TITLE
Updates metalite

### ISSUE THREAD

**Issue by ginnaram** [Merck/metalite#16]
metalite/default_parameter_ae.R updates required for the below for the ae0summary

"with no adverse event" category is not present in ae0summary r table, adam_mapping in metalite to be updated to add it
"grade 3-4 adverse event" not present in adam_mapping.
disc0ser0rel subset condition has to be updated in adam_mapping to add drug-related
dtc0rel subset condtion need to be updated with aesdth=="Y" instead of aesdtc == "Y"
discontinued drug1(ACN1), drug2(ACN2) categories need to be added
dose modification categories need to be added.

**Comment by ruchitpatel2002** [comment]
- metalite.ae::prepare_ae_summary update and under review for "with no adverse event" category.
- "grade 3-4 adverse event" added to default parameter list. PR merged.
- disc0ser0rel subset condition update. PR merged.
-  dtc0rel subset condition update. PR merged.
@ginnaram Discontinued drug1/drug 2 and dose modification categories  are sub-categories within bigger category. Will have to re-visit this later.

**Comment by elong0527** [comment]
@LittleBeannie , should we restructure the task and move to `metalite.ae`?

**Comment by fb-elong** [comment]
created in 

https://github.com/Merck/metalite.ae/issues/118
https://github.com/Merck/metalite.ae/issues/119
