### ISSUE TITLE
Bulletproof for `validate_adam_mapping()` not work

### ISSUE THREAD

**Issue by wangben718** [Merck/metalite#27]
We should expect an error for this case:
```
adam_mapping(
 name = "apat",
 id = "USUBJID",
 group = "TRT01A",
 subset = "TRTFL == 'Y'",
 label = "All Participants as Treated"
 )
```

**Comment by elong0527** [comment]
More detail is required to explain why an error is expected. 

If you expect `var` is required, that's not necessary as the output display `NULL`. 

```
ADaM mapping: 
* `name`   -> "apat"
* `id`     -> "USUBJID"
* `group`  -> "TRT01A"
* `var`    -> NULL
* `subset` -> "TRTFL == 'Y'"
* `label`  -> "All Participants as Treated"
```

**Comment by wangben718** [comment]
> More detail is required to explain why an error is expected.
> 
> If you expect `var` is required, that's not necessary as the output display `NULL`.
> 
> ```
> ADaM mapping: 
> * `name`   -> "apat"
> * `id`     -> "USUBJID"
> * `group`  -> "TRT01A"
> * `var`    -> NULL
> * `subset` -> "TRTFL == 'Y'"
> * `label`  -> "All Participants as Treated"
> ```

It is reasonable for me now. Thanks for checking!
