### ISSUE TITLE
Remove the use of triple colon operators

### ISSUE THREAD

**Issue by nanxstats** [Merck/metalite#3]
From the [R CMD check](https://github.com/Merck/metalite/runs/6488518222?check_suite_focus=true#step:6:74), I see

```
* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘r2rtf:::as_rtf_new_page’
  See the note in ?`:::` about the use of this operator.
```

Since `r2rtf:::as_rtf_new_page()` is simply defined as:

```r
function () paste("{\\pard\\fs2\\par}\\page{\\pard\\fs2\\par}")
```

To eliminate the note, you can either 1) export it in r2rtf or 2) copy it as an internal function to this package.

**Comment by nanxstats** [comment]
I having a mixed feeling about the `getFromNamespace()` trick mentioned in the SO answer. Feels to me it's not a permanent solution and can be even harmful: it can easily break the package once the upstream private API changes. 🤔 

But I do agree this can be handled later when appropriate.

**Comment by elong0527** [comment]
The dependency has been removed. Closing the issue.
