### ISSUE TITLE
Independent testing for `meta_split.R`

### ISSUE THREAD

**Issue by wangben718** [Merck/metalite#31]
Test plan of `meta_split()`:

Devide meta into groups by "SEX", run `meta_dummy() |> meta_split("SEX")`. (check whether meta is split and use snapshot testing)

**Comment by howardbaek** [comment]
I'm confused as to what variable to split by. Do I run `meta_dummy() |> meta_split("RACE")` `meta_dummy() |> meta_split("SEX")` or both?

**Comment by wangben718** [comment]
Hi @howardbaek , actually either is ok. I have revised the test plan. Sorry for the inconvenience.
