### ISSUE TITLE
Independent testing of `meta_validate.R`

### ISSUE THREAD

**Issue by wangben718** [Merck/metalite#32]
Test plan of `meta_validate()`:
1. use `meta_dummy()` as input. Will return the same meta
2. Check `data_type`: set `meta <- meta_summy()`. 
    Change `meta$data_population` into `NULL`. Run `meta_validate(meta)` will throw an error
    Change `meta$data_observation` into `NULL`. Run `meta_validate(meta)` will throw an error
    Change `meta$plan` into `NULL`. Run `meta_validate(meta)` will throw an error
3. Check plan variable name: set `meta <- meta_summy()`. 
   Change `meta$plan` variable name by using `names(meta$plan)[5] <- "param"`. Run `meta_validate(meta)` will throw an error
4. Check id variable: set `meta <- meta_summy()`. 
   Change population id variable by `meta$population$apat$id <- "id"`. Run `meta_validate(meta)` will throw an error
5. Check label variable: set `meta <- meta_summy()`.  
   Change population label variable by `meta$population$apat$label <- NULL`. Run `meta_validate(meta)` will throw an warning message
6. Check observation variables in the datasets: 
    set `meta <- meta_summy()`. Change `meta$observation$wk12$id` into 'ID'. Run `meta_validate(meta)` will throw an error
    set `meta <- meta_summy()`. Change `meta$observation$wk12$group` into 'group'. Run `meta_validate(meta)` will throw an error
    set `meta <- meta_summy()`. Change `meta$observation$wk12$var` into 'var'. Run `meta_validate(meta)` will throw an error

**Comment by howardbaek** [comment]
Hi @wangben718 , for "6. Check observation variables in the datasets:", I'm a bit confused about the "Change XXX" part.

Is this what you meant? 

- Set `meta$observation$wk12$id <- "ID"`. Running `meta_validate(meta)` will throw an error.
- Set `meta$observation$wk12$group <- "group"`. Running `meta_validate(meta)` will throw an error.
- Set `meta$observation$wk12$var<- "var"`. Running `meta_validate(meta)` will throw an error.

**Comment by wangben718** [comment]
Hi @howardbaek . Yes, you're right!
