### ISSUE TITLE
Validation and testing efforts

### ISSUE THREAD

**Issue by BrianLang** [Merck/metalite#4]
Hi, can we create a wish-list for validation/testing of this package? We have some potential contributors.

**Comment by elong0527** [comment]
@wangben718 , I tentatively assign this item to you. 

We may create one tickets for a group of relevant functions. 

Thanks!

**Comment by BrianLang** [comment]
I'd be available to do testing/address issues if needed.

**Comment by LittleBeannie** [comment]
Hi @BrianLang, the test plan of `metalite` is available at https://github.com/Merck/metalite/issues?q=is%3Aopen+is%3Aissue+label%3A%22independent+test%22. 
I currently assigned these tickets to Sarad, Madhu, Ben, Venkat, and Howard. Are you interested in testing some of the R functions?

**Comment by BrianLang** [comment]
Yes, sure. If you would reallocate some to me, I would have time to contribute. I didn't want to take issues that are already assigned in case someone was already working on them.

**Comment by LittleBeannie** [comment]
Thanks, @BrianLang! We just kicked off our tests of `metalite` this week. No worries, you are right on track!
We hold weekly meetings to gather questions. I will forward you the meeting link. How about discussing the test assignments during the meeting? If some group members have lots to carry on, I guess you can help take over some.

**Comment by BrianLang** [comment]
Sounds good. Thanks :-)
