### ISSUE TITLE
add a vignette to tutorial the A&R grid & mockup generation

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite#50]

**Comment by wangben718** [comment]
Hi @LittleBeannie , I can work on this issue since I am trying to review some old vignettes from metalite gallery.

-Ben

**Comment by LittleBeannie** [comment]
> Hi @LittleBeannie , I can work on this issue since I am trying to review some old vignettes from metalite gallery.
> 
> -Ben

Thanks, @wangben718!
