### ISSUE TITLE
Independent testing for `label.R`

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite#78]
Test plan for `get_label`:

- It returns the columns when the input data has no labels, i.e., the output of
```
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
get_label(tbl)
```
is `"a", "b"`
- It returns the labels when the input data has labels, i.e., the output of 
```
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
attr(tbl[[1]], "label") <- "variable 1"
attr(tbl[[2]], "label") <- "variable 2"
get_label(tbl)
```
is `"variable 1", "variable 2"`

**Comment by LittleBeannie** [comment]
Test plan for `assign_lable`:
- It gives an error message when you run
````
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
assin_label(tbl, var = "a", label = c("variable 1", "variable 2"))
```
- It gives an error message when you run
````
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
assin_label(tbl, var = c("a", "a"), label = c("variable 1", "variable 2"))
```
- It gives a warning message when you run
````
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
assin_label(tbl, var = "a", label = "variable 1")
```
- After running the following code, the labels of `tbl` is `"variable 1", "variable 2"`
````
tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
assin_label(tbl, var = c("a", "b"), label = c("variable 1", "variable 2"))
```

**Comment by ginnaram13** [comment]
> 

Hi @LittleBeannie 

Can you check why the label is not assigning for below;

tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3))
assign_label(tbl, var = c("a", "b"), label = c("variable 1", "variable 2"))

![image](https://user-images.githubusercontent.com/103939323/191055547-17ae165a-51f8-4bea-82c8-6ed5fe35d219.png)

**Comment by LittleBeannie** [comment]
> > 
> 
> Hi @LittleBeannie
> 
> Can you check why the label is not assigning for below;
> 
> tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3)) assign_label(tbl, var = c("a", "b"), label = c("variable 1", "variable 2"))
> 
> ![image](https://user-images.githubusercontent.com/103939323/191055547-17ae165a-51f8-4bea-82c8-6ed5fe35d219.png)

Hi @ginnaram13 , please try `tbl$a` and you will find `a`'s label is `variable 1`.

**Comment by ginnaram13** [comment]
> > > 
> > 
> > 
> > Hi @LittleBeannie
> > Can you check why the label is not assigning for below;
> > tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3)) assign_label(tbl, var = c("a", "b"), label = c("variable 1", "variable 2"))
> > ![image](https://user-images.githubusercontent.com/103939323/191055547-17ae165a-51f8-4bea-82c8-6ed5fe35d219.png)
> 
> Hi @ginnaram13 , please try `tbl$a` and you will find `a`'s label is `variable 1`.

@LittleBeannie 
No Luck for me
![image](https://user-images.githubusercontent.com/103939323/191078920-1d8c3ec4-1ed2-499b-acac-31c1968379bf.png)

**Comment by ginnaram13** [comment]
> > > > 
> > > 
> > > 
> > > Hi @LittleBeannie
> > > Can you check why the label is not assigning for below;
> > > tbl <- data.frame(a = c(1, 2, 3), b = c(-1, -2, -3)) assign_label(tbl, var = c("a", "b"), label = c("variable 1", "variable 2"))
> > > ![image](https://user-images.githubusercontent.com/103939323/191055547-17ae165a-51f8-4bea-82c8-6ed5fe35d219.png)
> > 
> > 
> > Hi @ginnaram13 , please try `tbl$a` and you will find `a`'s label is `variable 1`.
> 
> @LittleBeannie No Luck for me ![image](https://user-images.githubusercontent.com/103939323/191078920-1d8c3ec4-1ed2-499b-acac-31c1968379bf.png)

![image](https://user-images.githubusercontent.com/103939323/191079255-81e8057b-f74a-45f7-bc89-71579f2949e0.png)
